name: checking_gui_code
on:
  push:
    branches:
      - 'gui/**'

env:
  EXECUTABLES:
    "zappy_gui"

jobs:
  compilation:
    name: check_compilation_gui
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checking gui binary
        run: |
          echo "${{ env.EXECUTABLES}}"
          for exec in $(echo "${{ env.EXECUTABLES}}" | tr "," " "); do
            if [ ! -f "$exec" ]; then
              echo "::error file=$exec,title=Binary::Binary not found"
              exit 1
            fi
          done
