name: checking_gui_code
on:
  push:
    branches:
      - 'gui/**'

jobs:
  build_gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile_gui
        run: make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zappy_gui
          path: ./zappy_gui

  check_compilation_gui:
    name: check_compilation_gui
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: zappy_gui
      - name: checking gui binary
        run: |
          echo "${{ env.EXECUTABLES}}"
          for exec in $(echo "${{ env.EXECUTABLES}}" | tr "," " "); do
            if [ ! -f "$exec" ]; then
              echo "::error file=$exec,title=Binary::Binary not found"
              exit 1
            fi
          done
        env:
          EXECUTABLES: zappy_gui