name: check_if_project_is_valid
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

env:
  MIRROR_URL:
    git@github.com:EpitechPromo2027/B-YEP-400-REN-4-1-zappy-maxence.largeot.git
  EXECUTABLES:
    "zappy_server zappy_gui zappy_ai"

jobs:
  build_gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile_gui
        run: make
      - name: List files
        run: ls -la
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zappy_gui
          path: ./zappy_gui

  build_ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile_ai
        run: make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zappy_ai
          path: ./zappy_ai

  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile_server
        run: make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zappy_server
          path: ./zappy_server

  check_compilation:
    name: check_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts gui
        uses: actions/download-artifact@v4
        with:
          name: zappy_gui
      - name: Download artifacts ai
        uses: actions/download-artifact@v4
        with:
          name: zappy_ai
      - name: Download artifacts server
        uses: actions/download-artifact@v4
        with:
          name: zappy_server
      - name: checking binary exist
        run: |
          echo "${{ env.EXECUTABLES}}"
          for exec in $(echo "${{ env.EXECUTABLES}}" | tr "," " "); do
            if [ ! -f "$exec" ]; then
              echo "::error file=$exec,title=Binary::Binary not found"
              exit 1
            fi
          done

  push_to_mirror:
    if : github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}